### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by cl3m** [SRGSSR/srgmediaplayer-apple#25]
### Issue overview

Chromecast support would be a great even on iOS. Many media player do support it (ARTE, Vimeo, YouTube, ..). More info at https://developers.google.com/cast/docs/developers

* [ ] Incorrect behavior
* [X] Feature request
* [ ] Crash
* [ ] Help / documentation
* [ ] Other: _classification_

**Comment by defagos** [comment]
Sorry for the late answer. Yes, this is definitely something we intend to deliver in a hopefully not so distant future. What remains to be investigated is whether Chromecast support must be actually implemented in the library or not.

Given the recent changes of Chromecast V3, it seems possible that Chromecast support could be better implemented at the application level. We should provide all necessary hooks in our library, of course. We could maybe provide a companion framework as well to fill the gap.

**Comment by defagos** [comment]
Sorry for the late answer. Yes, this is something we are planning to add in a not so distant future (cannot tell you exactly when for the moment).

With the recent Chromecast V3 changes, though, it remains to be investigated whether this feature should be added to our library directly (probably as an optional dependency), or whether it would be best done at the app level (in which case we would provide all necessary hooks and sample code for integration, maybe a companion framework).

**Comment by defagos** [comment]
The implementation of Google Cast in our application (itself based on SRG MediaPlayer) is almost finished, and I now understand how Google Cast works and how it must be integrated in applications. I can therefore properly answer your feature request:

* The way Google Cast works is far different from the way AirPlay works. AirPlay works by having the local `AVPlayer` instance seamlessly transform into a proxy for content played on the receiver. Integrating Google Cast, though, is rather integrating shared remote controls for content played on the receiver. 
* When you want to play some content with Google Cast, you just supply metadata and a URL to the receiver by sending all information through the Google Cast SDK. No `AVPlayer` instance is required at all. In fact, you could imagine having a Google Cast compatible application which can itself not play any media on the device.
* With Google Cast, the central authority for content currently being played is the receiver. Once a Google Cast receiver is available, any application using the Google Cast SDK can access information about what is being played and can display a tiny and / or large remote control view to manage playback. With AirPlay, the central authority remains the device itself, not the receiver.
* Any content being played on the Google Cast receiver (including content stemming from another app or device) can be managed within these remote control views, in any other application, which is quite different from AirPlay, which is tightly coupled to an `AVPlayer` instance from a single application. 
* How those remote control views are integrated strongly depends on the application itself, most notably how its view or view controller hierarchy has been designed.
* Finally, Google Cast must be integrated with CocoaPods, which interferes with how we distribute SRG MediaPlayer through Carthage. I attempted integration with Carthage and a custom binary repository. Redundancy of the Protobufs library with other Google SDKs integrated with CocoaPods (most notably Firebase), though, makes such integration unreliable because of duplicate symbols.

For all these reasons, I am now convinced that **SRG MediaPlayer cannot provide any Google Cast integration**. SRG MediaPlayer controller is strongly related to an `AVPlayer` instance and therefore promotes SRG MediaPlayer controllers as authorities to control playback. This is in direct opposition to how Google Cast works, with the receiver being the playback authority, and the device only a remote control.

Google Cast integration is moreover the responsibility of the application itself, since SRG MediaPlayer must not make any assumptions about the view controller hierarchy and how Google Cast player views should be presented. Moreover, SRG MediaPlayer has no access to metadata information it could supply to Google Cast, unlike the application itself. Attempting to provide additional abstractions to provide for such flexibility at the SRG MediaPlayer level would lead to additional complexity.
