### ISSUE TITLE
Xcode 8 can't build SRGMediaPlayer module

### ISSUE THREAD

**Issue by vpdn** [SRGSSR/srgmediaplayer-apple#5]
### Issue overview
- [ ] Incorrect behavior
- [ ] Feature request
- [ ] Crash
- [ ] Help / documentation
- [X] Other: Build issue
### Description of the problem

I’m encountering an issue during the migration to Xcode 8. After removing all other dependencies, it seems to problem might lie in the Podfile/Configuration of the player. I’ve created a new sample swift project in Xcode 8 and added a bridging header. When I try to bridge SRGMediaPlayer to use with swift, I get the following error: 

```
Could not build module ‚SRGMediaPlayer’
```
### Environment information

Xcode 8
CocoaPods 1.0.1
### Reproducibility
- [X] Always reproducible
- [ ] Difficult to reproduce
### Code sample

See [attached](https://github.com/SRGSSR/SRGMediaPlayer-iOS/files/481669/PlayerTest.zip).
### Steps to reproduce

1) Open the sample workspace in Xcode 8. The project should compile fine.
2) Now open up the bridging header (PlayerTest-Bridging-Header.h) and uncomment the import of the SRGMediaPlayer.

=> You should now get the error mentioned above.

It seems the problem is specific to the project, since adding and bridging another one works fine. I’ve added FXReachability as a counter example of a podspec that works.

**Comment by defagos** [comment]
You use the `use_frameworks!` Podfile flag. This means FXReachability and SRGMediaPlayer are bundled as frameworks dependencies. Since you are importing FXReachability with an import directive in your app delegate, it works, but you don’t do the same with our SRGMediaPlayer module in your view controller and for this reason it fails.

There are two ways of solving your issue:
1.  (recommended) You leave the `use_frameworks!` flag in your Podfile and you import all your pods with `import` directives where needed. If all the Objective-C code you have in your app is included by your Pods, you can also completely drop the bridging header, as .framework module information provides all the needed information to use Objective-C frameworks with Swift this way
2. You drop the `use_frameworks!` flag and you `#import <SRGMediaPlayer/SRGMediaPlayer.h>` (and other pods similarly) in your bridging header. You can then use our classes from your Swift code base without any additional imports

This information was missing from our readme file, sorry. I added it to the readme on master directly (I did not create an official tag for this documentation update, though).

Thanks for your feedback.

Best regards.
