### ISSUE TITLE
Play failed with URL not end with extension.

### ISSUE THREAD

**Issue by cowboybkit** [SRGSSR/srgmediaplayer-apple#6]
I have a link like: http://av1.aliez.me/video/1/9/50119.mp4?st=CSy-zGAEoVIUACeJOmq7uw.
But SRGMediaPlayer can not play

**Comment by vpdn** [comment]
> But SRGMediaPlayer can not play

I think it might be helpful if you could provide details what you've tried and show some code. Did a quick test, the video works with SRGMediaPlayer (screenshot below). Since it's http, could it be that your app has ATS enabled and blocks the URL? 

![simulator screen shot 21 dec 2016 11 37 50](https://cloud.githubusercontent.com/assets/387312/21386188/f03a2d54-c771-11e6-8e8c-bb1b78c21e88.png)

**Comment by cowboybkit** [comment]
Hi,

I copied RTSMediaPlayerViewController(.h, .m, .xib) and RTSMediaPlayerSharedController (.h, .m) to my project and rename to customize . Then I play this link is not work. It show message:

> [RTSMediaPlayer] Playback did fail: Error Domain=AVFoundationErrorDomain Code=-11828 "Cannot Open" UserInfo={NSUnderlyingError=0x17025e090 {Error Domain=NSOSStatusErrorDomain Code=-12847 "(null)"}, NSLocalizedFailureReason=This media format is not supported., NSLocalizedDescription=Cannot Open}

Here is my files
[Archive.zip](https://github.com/SRGSSR/SRGMediaPlayer-iOS/files/670239/Archive.zip)

PS: I checked ATS disabled. The link play with RTSMediaPlayerViewController is working.

**Comment by cowboybkit** [comment]
Hi, 
I found problems here, need set 
`[self setIdentifier]`

Then it work right.
