### ISSUE TITLE
Device lock has to be prevented while playing a video over AirPlay audio device only

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srgmediaplayer-apple#87]
### Issue type
Incorrect behavior

### Description of the problem

When playing a video over AirPlay audio only (Apple AirPort Express, Sono…), the device turns off after the iOS settings delay.

Play SRF, AppStore review:
> Grundsätzlich eine gute App! Leider dunkelt der Bildschirm seit einem der letzten Updates beim Schauen von Videos nach einer gewissen Zeit automatisch ab und schaltet schliesslich ganz aus. Damit ist das Videoschauen relativ mühsam.. Wäre schön, wenn das demnächst behoben werden könnte..
Nachtrag: Das Abdunkeln geschieht nur,  wenn der Ton via AirPlay (Sonos) wiedergegeben wird. Das Problem besteht auch im Vollbildmodus. Zeitlich passiert es abhängig von der Einstellung der Anzeige bzgl. Automatischer Sperre (aktuell 2min). Hintergrundwiedergabe ist aktiv. App-Version: 3.1.0; iOS: 13.5.1

This issue comes from #84 . Probably from [this part of code](https://github.com/SRGSSR/srgmediaplayer-apple/blob/06e5259f5b34c12b01e1e03718b5cc35612b5cf5/Framework/Sources/Controllers/SRGMediaPlayerController.m#L1376).

### Environment information

* Library version: 5.0.0
* iOS version: 12+
* Device: Any

### Reproducibility

Always reproducible

### Code sample

[Play iOS code in production](https://github.com/srgssr/srgplay-ios)

### Steps to reproduce

I was abled to reproduce in Letterbox Demo and Play SRG apps easily.

1. Connect an iOS. device to an AirPlay audio only device.
2. Set "Auto-Lock" to 30 sec (in iOS. Settings / Display & Brightness)
3. Open a Play apps, and Play a video: video is on the device screen, sound is on the external audio device.
4. Wait 30 seconds without touching he screen.

**Current result:** The device screen turns OFF.

**Expected result:** The device screen prevents to turn OFF.

**Comment by defagos** [comment]
Thanks, was just gonna create this issue to write this comment. And I now just saw that you have a fix proposal as well, and that we named our branches quite similarly. We are probably two parts of the same brain :)

I have a sligthly different fix proposal than yours, but at the same location. I think it should suffice to test whether external playback is active or not instead of the current condition. I cannot test this intuition entirely with my setup (I can only simulate it by setting `usesExternalPlaybackWhileExternalScreenIsActive` to `NO`).

The idea is:

- The current test is not sufficient. AirPlay is active as soon as something goes over it, whether it is video or video + sound, so the condition breaks for an AirPlay 2 speaker for which audio is sent over AirPlay but video stays on device.
- If I remember well, `externalPlaybackActive` is `YES` if and only if **video** playback occurs externally. So I think the last part of your test condition is actually implicit, thus the simpler test I propose.

I'll let you have a look next week, as you have such a device at home. My fix is on `feature/airplay-audio-only-fix`, yours on `feature/airplay-audio-only`.

**Comment by pyby** [comment]
I didn't mention my fix yet because:
- I also tried to check the media type `self.mediaType == SRGMediaPlayerMediaTypeVideo`, but `self.mediaType` is known to not be fully trusted over AirPlay. Probably the reason why my tests failed (Open the application, then the player with a VoD over Airplay already configured). ❌
- Idea to use `externalPlaybackActive` seems a good way. _Indicates whether the player is currently playing video in "external playback" mode._
- I was asking myself about audio over AirPlay, AirPlay mirroring for video and audio. You're right, `AVPlayer` already manages the media type, regarding the `externalPlaybackActive` property.

Your fix branch works as expected, tested on my side. (Letterbox Demo and Play SRG debug). Thank you.
